### ISSUE TITLE
Don't pin release

### ISSUE THREAD

**Issue by fabaff** [happyleavesaoc/python-crimereports#1]
`requests` is pinned to a specific release (`install_requires=['requests==2.12.4'],`). This avoid the installation in Home Assistant.

Please remove the pinning.

**Comment by fabaff** [comment]
Was fixed with https://github.com/happyleavesaoc/python-crimereports/commit/bab7c04a54b9886e7f026963e879ec3d6ce22f1f

**Comment by fabaff** [comment]
@happyleavesaoc, can you please create a new release and publish it on PyPI? Thanks.

**Comment by happyleavesaoc** [comment]
@fabaff pushed `1.0.1` to pypi.

**Comment by fabaff** [comment]
Cool. Thanks a lot.
